[package]
name = "ulpf"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "ulpf"
path = "src/main.rs"

[dependencies]
ulpf-time = { path = "../ulpf-time" }
ulpf-store = { path = "../ulpf-store" }
ulpf-parse = { path = "../ulpf-parse" }
ulpf-normalize = { path = "../ulpf-normalize" }
