[package]
name = "ulpf-parse"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ulpf-time = { path = "../ulpf-time" }
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
regex.workspace = true
memchr.workspace = true
xmlparser.workspace = true

[dev-dependencies]
ulpf-store = { path = "../ulpf-store" }
